version: '3.8'

services:
  api:
    build: .
    container_name: blog-service-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - APP_ENV=docker
      - DATABASE_URL=postgres://postgres:postgres@db:5432/blog_service?sslmode=disable
      - PORT=8080
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID}
      - OAUTH_GITHUB_CLIENT_SECRET=${OAUTH_GITHUB_CLIENT_SECRET}
      - OAUTH_GITHUB_REDIRECT_URL=${OAUTH_GITHUB_REDIRECT_URL}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - OAUTH_GOOGLE_REDIRECT_URL=${OAUTH_GOOGLE_REDIRECT_URL}
      - OAUTH_VK_CLIENT_ID=${OAUTH_VK_CLIENT_ID}
      - OAUTH_VK_CLIENT_SECRET=${OAUTH_VK_CLIENT_SECRET}
      - OAUTH_VK_REDIRECT_URL=${OAUTH_VK_REDIRECT_URL}
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    container_name: blog-service-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog_service
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
