app:
  name: "blog-service"
  version: "1.0.0"

server:
  port: "8080"
  host: "localhost"

jwt:
  secret_key: ${JWT_SECRET}
  expires_in: "24h"

database:
  host: "localhost"
  port: "5432"
  name: "blog_db"
  user: "postgres"
  password: "postgres"
