server:
  port: 8080
  read_timeout: 60s
  write_timeout: 60s

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  ssl_mode: disable

auth:
  jwt_secret: ${JWT_SECRET}
  token_ttl: 86400 # 24 hours
